name: Test
on:
  push:
  workflow_dispatch:

jobs:
  prosody-0_12:
      name: Test prosody 0.12
      runs-on: ubuntu-24.04
      steps:
        - uses: actions/checkout@v4.2.2
        - uses: hoverkraft-tech/compose-action@v2.2.0
          with:
            compose-file: "./compose.yaml"
          env:
            PROSODY_VERSION: "0.12"
        - name: Test
          run: |
            sh test_openssl.sh
